// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Operations defines a contract for the operations described by OpenAPI v3 specification.
type defaultOperations interface {
	// FooBarBazGet implements GET /foo/bar/baz operation.
	//
	// GET /foo/bar/baz
	FooBarBazGet(ctx context.Context) (string, error)
	// FooBarQuxGet implements GET /foo/bar/qux operation.
	//
	// GET /foo/bar/qux
	FooBarQuxGet(ctx context.Context) (string, error)
	// FooParamXyzGet implements GET /foo/{param}/xyz operation.
	//
	// GET /foo/{param}/xyz
	FooParamXyzGet(ctx context.Context, params FooParamXyzGetParams) (string, error)
}

type Operations interface {
	defaultOperations
}
